version: '3.7'

services:
  database:
    container_name: database
    image: postgres:latest
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - nest-db:/var/lib/postgresql/data
    restart: always
    networks:
      - nest-net
  test-database:
    container_name: e2e-database
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: nest-testing
    volumes:
      - test-db:/var/lib/postgresql/data
    networks:
      - nest-net

networks:
  nest-net:
    name: nest-network
    driver: bridge

volumes:
  nest-db:
    name: nest-database
  test-db:
    name: nest-test-database
